name: Check NC4 Links

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch:

jobs:
  check_links:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4 pandas

    - name: Check NC4 Links
      run: |
        python check_nc4_links.py

    - name: Read new links flag
      id: read_flag
      run: |
        new_links_flag=$(cat new_links_flag.txt)
        echo "::set-output name=new_links::$new_links_flag"

    - name: Commit and push the results
      if: steps.read_flag.outputs.new_links == 'True'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git add results.csv
        git commit -m 'Update NC4 links'
        git push origin HEAD:${{ github.ref }}
